//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceNow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class insuranceEntities : DbContext
    {
        public insuranceEntities()
            : base("name=insuranceEntities")
        {
        }

        public string Policy { get; internal set; }
        public DateTime? Expiry { get; internal set; }
        public string Location { get; internal set; }
        public string State { get; internal set; }
        public string Region { get; internal set; }
        public Double? InsuredValue { get; internal set; }
        public string Construction { get; internal set; }
        public string BusinessType { get; internal set; }
        public string Earthquake { get; internal set; }
        public string Flood { get; internal set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    }
}
